sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: EGQqi78a+S+Q4SSz57/hwZntv8HyevjWn/pPMwLR9siEPY45Tq1vuBbWV9XxZfE5AbddtLoNiJEhiXDSevM5W+nwhMTz837To/6L7QTnNkOhXgurOiaKTjYte5UPjpO6nS4qZitxg4YdndAcrg1OPUp6njtO4+qik1W3ELsk65HJ36GcV8bmsKOsKjajzxAB8b9Ko4jCJxvgHbVI1vvlFzOKMgtXh/BAfBlM1rgqkVFFdi0XYqDh0f6XgtlkrRRHJ9B5GpAGRqHOq7l+/81hLwOjypm3ymV8Y7nN9Ax1f/jYzP1iqZoFK+mh2VlPz7Sw725XMl1uOpxawcl3JiPrukTyOLfmh1C3tQwEJre4X4PwQssFKFkqAIScgOstQskBSGEhaXg2NmjgwvEt5/GLskRIKeO48G+ppIqV6X+ONEuigU91Zh/+9fuAvS+9yS+zV6n08j3EGxDKGe6JFCDdAMmu0Y2tZ3ZM8+5gCcPriEDtUFKld4rlpQOTB1YPkVVcwylxnGvJC+YXcuzLVM43cdbrxHbrKtIdPp0hl4p7vSMOJ25Gc9Q1Bn1ZNfHdHj87N4vX2xGHhE9CZq5l8RzZ/3pDkHNDCK1J/ywdsYOdIRWoSxqm1VxlcV90gXaoFXvxcTUOygHQ5d6ptmwAE1xWRgaoECJkR8SChglP038xl8E=
    - secure: nadTd1CyyHjes39WZEB22Sj0jozD9a/eqyk+WBL6cv7g1XBujX10UifvCHlvv1oAmc7AAVuqQkinlSP1do9eQXIygpC09cERR84mlInIektnLFt5dvp92z+13VCPq9ZSsxSv/UxY2ln7t6iwO9cGBEnTsJJSSxsHPwWhBkwv4OJLyahoKu482GBA5kulwy0yJ7hKdBgFpVxmpMuYg31tvZsv1hE9HHprjwcg7ayC+KzUzXbpqFvHzgxlJcnfLCBi7Uq8fa67ooeSGHbvDD5rZXKXJZg1t97vdvTrxFbTsaP3GHEnWfwCKjkOecpnl5O4eTx60WNahFwlXIooo5Eqy11rQp5qR06zUAwZS3iRUdLUMHwyqpWDHqyEF6r6aJq/kE8ARrHIKckNxjIdMCIHBKZ30mxEGnS4viDOoMo31ZsDxtchiUtgROmtG98oWXSB3dzy9SzpbkoQHv6jrJt9zpu+OQovqpo3wxwj9p04wb49QMjSpIXpNLLiiA26L7nEMfzMOhb2cZL5NopassyuhxHTOEDzW7j/X0Su7bcI/0rgmKbd8jHGhYx7gRmfywX/BCGcT2Np5N4sNLV+Zw+Ltqm6rqaDlY1gBwL9Tz4EB61E1fUD0S4xFHBIWn+Tx4fOEnEakH2n5O3isK7ElytNIuXEHmTea7DF6L9zYrNJK8Q=
